name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Create Production Environment Variables
        run: |
          echo "NEXT_PUBLIC_AI_SERVER_URL=${{ secrets.NEXT_PUBLIC_AI_SERVER_URL }}" >> .env.production
          echo "AI_PROXY_TARGET=${{ secrets.AI_PROXY_TARGET }}" >> .env.production

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'ribeiro-labs-frontend'
          region: 'europe-west1'
          source: '.'

      - name: Show Output
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
